---
output:
  word_document: default
  html_document: default
---
# David Wells
## Module 4 Assignment 4
#
Load-in Libraries
```{r Load-in libraries, message=FALSE, include=FALSE}
library(tidyverse)
library(tidymodels)
library(caret)
library(gridExtra)
library(skimr)
library(vip)
library(ranger)
```
#
Load-in Data and Cleaning
```{r Load-in Data}
drug <- read_csv("~/BAN 502/Module 4/drug_data-1.csv")

names(drug) = c("ID", "Age", "Gender", "Education", "Country", "Ethnicity",
"Nscore", "Escore", "Oscore", "Ascore", "Cscore", "Impulsive",
"SS", "Alcohol", "Amphet", "Amyl", "Benzos", "Caff", "Cannabis",
"Choc", "Coke", "Crack", "Ecstasy", "Heroin", "Ketamine", "Legalh",
"LSD", "Meth", "Mushrooms", "Nicotine", "Semer", "VSA")

drug[drug == "CL0"] = "No"
drug[drug == "CL1"] = "No"
drug[drug == "CL2"] = "Yes"
drug[drug == "CL3"] = "Yes"
drug[drug == "CL4"] = "Yes"
drug[drug == "CL5"] = "Yes"
drug[drug == "CL6"] = "Yes"

drug_clean = drug %>% mutate_at(vars(Age:Ethnicity), funs(as_factor)) %>%
mutate(Age = factor(Age, labels = c("18_24", "25_34", "35_44",
"45_54", "55_64", "65_"))) %>%
mutate(Gender = factor(Gender, labels = c("Male", "Female"))) %>%
mutate(Education = factor(Education, labels =
c("Under16", "At16", "At17", "At18", "SomeCollege",
"ProfessionalCert", "Bachelors", "Masters", "Doctorate"))) %>%
mutate(Country = factor(Country,
labels = c("USA", "NewZealand", "Other", "Australia",
"Ireland","Canada","UK"))) %>%
mutate(Ethnicity = factor(Ethnicity,
labels = c("Black", "Asian", "White", "White/Black", "Other",
"White/Asian", "Black/Asian"))) %>%
mutate_at(vars(Alcohol:VSA), funs(as_factor)) %>%
select(-ID)

#str(drug_clean)

drug_clean = drug_clean %>% select(!(Alcohol:Mushrooms)) %>% select(!(Semer:VSA))
names(drug_clean)
```
#
Task 1
```{r Task 1}
skim(drug_clean)
# There doesn't seem to be any missing data.
```
#
Task 2
```{r Task 2}
set.seed(1234) 
drugc_split = initial_split(drug_clean, prop = 0.7, strata = Nicotine) #70% in training
train = training(drugc_split)
test = testing(drugc_split)
```
#
Task 3
```{r Task 3a}
p1 = ggplot(train, aes(x = Age, fill = Nicotine)) + geom_bar(position = "fill")
p2 = ggplot(train, aes(x = Gender, fill = Nicotine)) + geom_bar(position = "fill")
p3 = ggplot(train, aes(x = Education, fill = Nicotine)) + geom_bar(position = "fill")
p4 = ggplot(train, aes(x = Country, fill = Nicotine)) + geom_bar(position = "fill")
grid.arrange(p1,p2,p3,p4)
```
```{r Task 3b}
p5 = ggplot(train, aes(x = Ethnicity, fill = Nicotine)) + geom_bar(position = "fill")
grid.arrange(p1)
```
```{r Task 3c}
p6 = ggplot(train, aes(x = Nscore, fill = Nicotine)) + geom_bar(position = "fill")
p7 = ggplot(train, aes(x = Escore, fill = Nicotine)) + geom_bar(position = "fill")
p8 = ggplot(train, aes(x = Oscore, fill = Nicotine)) + geom_bar(position = "fill")
p9 = ggplot(train, aes(x = Ascore, fill = Nicotine)) + geom_bar(position = "fill")
grid.arrange(p1,p2,p3,p4)
```
```{r Task 3d}
p10 = ggplot(train, aes(x = Cscore, fill = Nicotine)) + geom_bar(position = "fill")
p11 = ggplot(train, aes(x = Impulsive, fill = Nicotine)) + geom_bar(position = "fill")
p12 = ggplot(train, aes(x = SS, fill = Nicotine)) + geom_bar(position = "fill")
grid.arrange(p1,p2,p3)
```
```{r Task 3e}
# From the visualizations, Age, Gender, Education, Country, and Ethnicity all seem to have some relationship with Nicotine use. Looking at the rest of the variables, it only looks like Escore does not have a relationship with Nicotine use.
```
#
Task 4
```{r Task 4}
set.seed(123)
rf_folds = vfold_cv(train, v = 5)

drug_recipe = recipe(Nicotine ~., train)

rf_model = rand_forest(mtry = tune(), min_n = tune(), trees = 100) %>%
  set_engine("ranger", importance = "permutation") %>% 
  set_mode("classification")

drug_wflow = 
  workflow() %>% 
  add_model(rf_model) %>% 
  add_recipe(drug_recipe)

rf_grid = grid_regular(
  mtry(range = c(2, 8)), 
  min_n(range = c(5, 20)), 
  levels = 10
)

set.seed(123)
rf_res_tuned = tune_grid(
  drug_wflow,
  resamples = rf_folds,
  grid = rf_grid 
)

rf_res_tuned %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  select(mean, min_n, mtry) %>%
  pivot_longer(min_n:mtry,
    values_to = "value",
    names_to = "parameter"
  ) %>%
  ggplot(aes(value, mean, color = parameter)) +
  geom_point(show.legend = FALSE) +
  facet_wrap(~parameter, scales = "free_x") +
  labs(x = NULL, y = "Accuracy")

rf_res_tuned %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  mutate(min_n = factor(min_n)) %>%
  ggplot(aes(mtry, mean, color = min_n)) +
  geom_line(alpha = 0.5, size = 1.5) +
  geom_point() +
  labs(y = "Accuracy")
```
#
Task 5
```{r Task 5}
best_rf = select_best(rf_res_tuned, "accuracy")

final_rf = finalize_workflow(
  drug_wflow,
  best_rf
)

final_rf

final_rf_fit = fit(final_rf, train)

final_rf_fit %>% pull_workflow_fit() %>% vip(geom = "point")

# From the chart, it appears that Age, Sensation Seeing (SS), and Openess to Experience (Oscore) are the most important variables.
```
#
Task 6
```{r Task 6a}
#Predictions on Training Set
trainpredrf = predict(final_rf_fit, train)
head(trainpredrf)

confusionMatrix(trainpredrf$.pred_class, train$Nicotine, 
                positive = "Yes")
```
```{r Task 6b}
# Predictions on Testing Set
testpredrf = predict(final_rf_fit, test)
head(testpredrf)
confusionMatrix(testpredrf$.pred_class, test$Nicotine, 
                positive = "Yes")
```
```{r Task 6c}
# The model had a 97% accuracy on the Training Set. The model had a 71% accuracy on the Testing Set. Assuming would  only yield a 67% accuracy rating. I don't feel very confident in this model.
```
#
Task 7
```{r Task 7}
# The model as is could be used to determine nicotine use in health insurance calculations, for example. The model may be able to accurately identify those individuals who do use nicotine; it may also however classify non-nicotine users as nicotine users. It may be, from a business case, better to over-classify nicotine users. Those individuals who are not nicotine users could have the classification changed with a minimum of impact. 

# I would not use this model, as I don't think it is precise enough. I would rather, and this is entirely a gut-feeling, have the Testing Set accuracy percentage in the 80+ range.
```




